### ISSUE TITLE
error in running docker build

### ISSUE THREAD

**Issue by jcl2023** [rhohndorf/Auto-Llama-cpp#22]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

when I ran  docker run  -p80:3000 auto-llama1, I got the following errors:

Welcome to Auto-Llama!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Traceback (most recent call last):
  File "/app/main.py", line 313, in <module>
    prompt = construct_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 205, in construct_prompt
    config = prompt_user()
             ^^^^^^^^^^^^^
  File "/app/main.py", line 231, in prompt_user
    ai_name = utils.clean_input("AI Name: ")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 3, in clean_input
    return input(prompt)
           ^^^^^^^^^^^^^
EOFError: EOF when reading a line

Any idea how to fix it?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by chiu0602** [comment]
It seems the application will not expose a port, so -p is not needed. Also can you try command below? It enable interactive tty for communicating to the app.
` docker run -it auto-llama1`
